services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    env_file: ../.env.all
    environment:
      NODE_ENV: development
    volumes:
      - ../server:/app/server
      - ../screens:/app/screens
      - ../content:/app/content
      - ../prompts:/app/prompts
    restart: unless-stopped
